### ISSUE TITLE
decoder_attentions in showAttentions does not sum up to 1 for each timestep

### ISSUE THREAD

**Issue by frankxu2004** [gau820827/AI-writer_Data2Doc#20]
When trying to show attention score for each generated token using `showAttention` function, I find that each row of the `decoder_attentions` does not sum up to 1, which seems strange for the attention mechanism. Most values are very small. Not sure if it is a bug?

**Comment by gau820827** [comment]
Close the issue since we're developing new models on the task and it's solved in fact.
