### ISSUE TITLE
Decoder -> Pointer-generator network (copy-mechanism)

### ISSUE THREAD

**Issue by yinhsunhuang** [gau820827/AI-writer_Data2Doc#5]

**Comment by frankxu2004** [comment]
I think this is important since the original paper compares several models incorporating the copying mechanism. I hope to see this coming a lot!

**Comment by yinhsunhuang** [comment]
I found that the original generating the P_vocab need to be a distribution of words. That is, a distribution of words. But in our case, we have a distribution over triplets (r_t, r_e, r_v). I don't know how to combine these two distribution.

**Comment by frankxu2004** [comment]
I think in the original paper, the copy action means that we care only about r_v to copy.
 "In our case, we assume that target words are copied from the value portion of a record r; that is, a copy implies yˆt = r.m for some r and t."

**Comment by yinhsunhuang** [comment]
That make sense. I see that section.

**Comment by frankxu2004** [comment]
BTW, have you checked the small evaluate now? at current setting and version, it could not run...

**Comment by yinhsunhuang** [comment]
It's in #19 now
